name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:    
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: 'ğŸ› Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: 'ğŸ§° Maintenance'
    labels: 
      - 'chore'
      - 'documentation'
      - 'dependencies'

  - title: 'ğŸ§ª Tests'
    labels:
      - 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  patch:
    labels:
      - 'release-patch'
  minor:
    labels:
      - 'release-minor'
  major:
    labels:
      - 'release-major'
  default: minor

template: |
  ## Whatâ€™s Changed

  $CHANGES